<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_bday_month</name>
   <tag></tag>
   <elementGuidId>d0a61c41-a600-4bc3-8f24-eb4594cb281e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name='birthday_month']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name='birthday_month']</value>
      <webElementGuid>644a16f2-a577-4fc8-93ab-ff3d16e9ba85</webElementGuid>
   </webElementProperties>
</WebElementEntity>
